Scrolling sidebar
Sberbank-Technology/ufs-react-doc pull request #39
Opened 2017-08-28 07:33 UTC by maximkochmin

2017-11-14 13:20 UTC, Luanre requested changes

2017-11-14 13:20 UTC, Luanre commented on src/common/ComponentList.tsx
> +        let sidebarTop = Math.max(111 - document.body.scrollTop, 0);
what is the `magic` constant `111`?

2017-11-14 13:31 UTC, maximkochmin commented on src/common/ComponentList.tsx
> +        let sidebarTop = Math.max(111 - document.body.scrollTop, 0);
it's like 666 but 6 times smaller!

2017-12-18 09:30 UTC, Luanre approved these changes

2017-12-18 09:30 UTC, merged