Added arrow components support
Sberbank-Technology/ufs-react-doc pull request #41
Opened 2017-11-08 10:29 UTC by Safort

2017-11-14 11:27 UTC, maximkochmin reviewed
Не разделяет Own Props и Inherited

2017-11-14 11:27 UTC, maximkochmin commented on src/utils/json-generators/typescript.ts
> +                if (isImportNode(path.node)) {
проверить, не парсит ли он сторонние либы

2017-11-14 11:27 UTC, maximkochmin commented on src/utils/json-generators/typescript.ts
> +        if (className == 'index') {
===

2017-11-14 11:35 UTC, maximkochmin requested changes
сложный гитхаб

2017-12-14 15:16 UTC, Luanre approved these changes

2017-12-14 15:36 UTC, merged